const objType = {
  INFO_USER: "INFO_USER",
  TOGGLE_SPINNERS: "TOGGLE_SPINNERS",
  UNMOUT_SPINNERS: "UNMOUT_SPINNERS",
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  TOKEN_USER: "TOKEN_USER",
  MESS: "MESS",
  GET_ALL_PRODUCTS_ON_CART: "GET_ALL_PRODUCTS_ON_CART",
  TANG_SO_LUONG: "TANG_SO_LUONG",
  MESS_ORDER: "MESS_ORDER",
  SEARCH_VALUE: "SEARCH_VALUE",
  EMPTY_INPUT: "EMPTY_INPUT",
  GET_ALL_FEEDBACK: "GET_ALL_FEEDBACK",
  GET_ALL_ORDERS: "GET_ALL_ORDERS",
  GET_HISTORY_ORDER: "GET_HISTORY_ORDER",
  UPDATE_ISACTIVE: "UPDATE_ISACTIVE",
  GET_ALL_USER: "GET_ALL_USER",
  GET_DETAILS: "GET_DETAILS"
};
export default objType;
